### ISSUE TITLE
Condicionais nas regras

### ISSUE THREAD

**Issue by mja-maia** [andersao/laravel-validator#13]
Estou criando um projeto onde preciso cadastrar um cliente, e o cliente pode ser pessoa física ou jurídica, e preciso validar o campo cpf como required se ele for pessoa fisica e o campo cnpj se for pessoa juridica, existe alguma maneira de criar uma condição de por exemplo:

chame as $rules X se for pessoa juridica e chame as $rules Y se for pessoa fisica

**Comment by edukmattos** [comment]
@mja-maia 
Conseguiste resolver ?
Pois estou passando pela mesma situação.
