### ISSUE TITLE
Compatibility with l5-repository

### ISSUE THREAD

**Issue by zepaduajr** [andersao/laravel-validator#20]
I can not use laravel-validator in version dev-master and L5-repository at the same time.

> "Prettus / laravel-validation": "1.1. *"

It would be possible to launch a release with the changes of custom messages (commit 64f66f70d1f291d30370cd255b1c75ac53351d80) ?

Thanks

**Comment by mvpasarel** [comment]
@zepaduajr This is how I load it in `composer.json` file:

```
"prettus/laravel-validation": "dev-develop as 1.1.4"
```

**Comment by zepaduajr** [comment]
@mvpasarel thanks. It works fine.
