### ISSUE TITLE
Add make:validator Command

### ISSUE THREAD

**Issue by ghost** [andersao/laravel-validator#5]
Just referencing [#53](https://github.com/prettus/l5-repository/issues/53) from [l5-repository](https://github.com/prettus/l5-repository) package

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by ghost** [comment]
@andersao  i just made a PR for this 
andersao/l5-repository#116
