### ISSUE TITLE
Validating unique 

### ISSUE THREAD

**Issue by astroanu** [andersao/laravel-validator#7]
This is my validation class, how does the validator automatically takes the id when updating an existing entity ? Do i need to pass the id? or just leave it. None seems to be working correctly.

```
class StudentValidator extends LaravelValidator {

    protected $rules = [
        'username' => 'required|unique:users,username,$id', // <--here
        'admission_date' => 'required|date',
        'first_name' => 'required',
        'last_name' => 'required'
    ];

}
```

**Comment by rajneeshojha** [comment]
you should make it like 
'required|unique:users,username,[id value],id'

**Comment by alanjholiveira** [comment]
Friend, I am also with same problem for unique validation, test this example without success.

**Comment by pedronalbert** [comment]
I have the same problem

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by motamonteiro** [comment]
I have the same problem.

**Comment by hugofabricio** [comment]
Someone could use?

**Comment by hugofabricio** [comment]
Set the id before rules in your controller.

Example: 

```
$this->validator->with($data)->setId($id)->passesOrFail(ValidatorInterface::RULE_UPDATE);
```

In your rules

`'username' => 'required|unique:users'`

**Comment by motamonteiro** [comment]
It worked fine,
Thanks!

**Comment by akatche** [comment]
Hello, i have a similar issue, how could i perform something like this

`'number' => 'required|numeric|unique:seasons,number,'.$season->id.',id,title_id,'.$season->title->id`

Because in this case i need to pass 2 params.
Thanks!

**Comment by tucq88** [comment]
@akatche it seems like you gonna need to create a custom method for generating your validation rules. I checked in code inside this package and see that it only allow 1 param and it's `ID` already.

**Comment by astroanu** [comment]
since the validator is using the Laravel convention if you pass column id, multiple id's with commas it should work

```
'column_to_validate' => 'unique:table_name,column_to_validate,id_to_ignore,other_column,value,other_column_2,value_2,other_column_N,value_N',
```

**Comment by hugofabricio** [comment]
Set the id before rules in your controller.

Example:

$this->validator->with($data)->setId($id)->passesOrFail(ValidatorInterface::RULE_UPDATE);
In your rules

'username' => 'required|unique:users'

**Comment by alexpersegona** [comment]
**setId($id)**
... now, ignoring unique columns on entity updates work, thanks @hugofabricio.

**Comment by Pierolin** [comment]
There are 2 layers to validate data. You can do it as following.
**1. Request Layer**
    public function rules()
    {
        $pathes = explode('/',$this::getPathInfo());
        $id = end($pathes);
        return ['username' => 'required|unique:users,username,' . $id];
   }

**2. Validator Layer**
**In Controller:**
$this->validator->with($data)->setId($id)->passesOrFail(ValidatorInterface::RULE_UPDATE);

**In Validator:**
protected $rules = [ValidatorInterface::RULE_UPDATE => ['username' => 'required|unique:users']];

Hope helped.
