### ISSUE TITLE
How to validate nested json and array?

### ISSUE THREAD

**Issue by DesmondPang** [andersao/laravel-validator#8]
I tried this but did not work.

```
  ValidatorInterface::RULE_CREATE => [
        'title'  => 'required|min:3',
        'extras.type' => 'required',
    ],
```

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
